=== gabrielrsilva11/TP_ID/livros.dtd
<!ELEMENT Catalogo (#PCDATA | livro)*>
<!ATTLIST Catalogo xmlns:xsi CDATA #IMPLIED>
<!ATTLIST Catalogo xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT livro (#PCDATA | titulo | cod_autor | editora | npaginas | preco | imagem)*>
<!ATTLIST livro isbn CDATA #IMPLIED>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT npaginas (#PCDATA)>
<!ELEMENT imagem (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editora (#PCDATA)>
<!ELEMENT cod_autor (#PCDATA)>

=== gabrielrsilva11/TP_ID/livros.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Catalogo SYSTEM "livros.dtd">
<Catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="livros.xsd">
     <livro isbn="9789726997948">
          <titulo>O Gigante Egoísta</titulo>
          <cod_autor>19398</cod_autor>
          <editora>Nova Vega</editora>
          <npaginas>40</npaginas>
          <preco>13.78</preco>
          <imagem>https://img.wook.pt/images/o-gigante-egoista-oscar-wilde/MXwxOTQxMDJ8MjQ1MTE2fDE0OTg2OTA4MDAwMDA=/260x</imagem>
     </livro>
     <livro isbn="978-972-0-72716-9">
          <titulo>O Menino-Estrela</titulo>
          <cod_autor>19398</cod_autor>
          <editora>Porto Editora</editora>
          <npaginas>64</npaginas>
          <preco>7.70</preco>
          <imagem>https://img.wook.pt/images/o-menino-estrela-oscar-wilde/MXwxNTg0MDI4N3wxNDg0Mjk1MXwxNDg1OTkzNjAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789892324517">
          <titulo>Relatório do Interior</titulo>
          <cod_autor>19587</cod_autor>
          <editora>Edições Asa</editora>
          <npaginas>288</npaginas>
          <preco>16.50</preco>
          <imagem>https://img.wook.pt/images/relatorio-do-interior-paul-auster/MXwxNTIyMjI2NnwxMDcwOTc1OXwxMzgzNTIzMjAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789892307657">
          <titulo>No País das Últimas Coisas</titulo>
          <cod_autor>19587</cod_autor>
          <editora>Edições Asa</editora>
          <npaginas>160</npaginas>
          <preco>14.90</preco>
          <imagem>https://img.wook.pt/images/no-pais-das-ultimas-coisas-paul-auster/MXw1MTAxNzc3fDMxNjkyODF8MTM4MzUyMzIwMDAwMA==/260x</imagem>
     </livro>
     <livro isbn="9789896413378">
          <titulo>Vinte Poemas de Amor e Uma Canção Desesperada</titulo>
          <cod_autor>19466</cod_autor>
          <editora>Relógio D'Água</editora>
          <npaginas>168</npaginas>
          <preco>12.00</preco>
          <imagem>https://img.wook.pt/images/vinte-poemas-de-amor-e-uma-cancao-desesperada-pablo-neruda/MXwxNDczMzI3MnwxMDIxNTIxMXwxMzgzNTIzMjAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789721060128">
          <titulo>Confesso que Vivi</titulo>
          <cod_autor>19466</cod_autor>
          <editora />
          <npaginas>352</npaginas>
          <preco>25.14</preco>
          <imagem>https://img.wook.pt/images/confesso-que-vivi-pablo-neruda/MXwxOTk1NjU4fDE3NjE3ODB8MTM4MzUyMzIwMDAwMA==/260x</imagem>
     </livro>
     <livro isbn="9788432212796">
          <titulo>Veinte Poemas De Amor Y Una Cancion Desesperada</titulo>
          <cod_autor>19466</cod_autor>
          <editora>SEIX BARRAL</editora>
          <npaginas>64</npaginas>
          <preco>7.64</preco>
          <imagem>https://img.wook.pt/images/veinte-poemas-de-amor-y-una-cancion-desesperada-pablo-neruda/MXwzNzMwNzYzfDI3MTYyNzh8MTM4MzUyMzIwMDAwMA==/260x</imagem>
     </livro>
     <livro isbn="9781944682989">
          <titulo>Grapes And The Wind</titulo>
          <cod_autor>19466</cod_autor>
          <editora>Spuyten Duyvil</editora>
          <npaginas>344</npaginas>
          <preco>19.58</preco>
          <imagem>https://img.wook.pt/images/grapes-and-the-wind-pablo-neruda/MXwyMTI3Njc5MHwxNzE0ODUyOXwxNTIwODEyODAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789721061156">
          <titulo>Nasci Para Nascer</titulo>
          <cod_autor>19466</cod_autor>
          <editora />
          <npaginas>320</npaginas>
          <preco>24.98</preco>
          <imagem>https://img.wook.pt/images/nasci-para-nascer-pablo-neruda/MXw5NTczMTU2fDUxNjExMzl8MTM4MzUyMzIwMDAwMA==/260x</imagem>
     </livro>
     <livro isbn="9789896412142">
          <titulo>O Desconhecido do Norte Expresso</titulo>
          <cod_autor>19537</cod_autor>
          <editora>Relógio D'Água</editora>
          <npaginas>280</npaginas>
          <preco>16.00</preco>
          <imagem>https://img.wook.pt/images/o-desconhecido-do-norte-expresso-patricia-highsmith/MXwxNTYyNjU5NHwxMTEyMDQ3N3wxMzkzNDU5MjAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789896417246">
          <titulo>Ripley Debaixo de Água</titulo>
          <cod_autor>19537</cod_autor>
          <editora>Relógio D'Água</editora>
          <npaginas>312</npaginas>
          <preco>16.00</preco>
          <imagem>https://img.wook.pt/images/ripley-debaixo-de-agua-patricia-highsmith/MXwxOTMzNzIxOXwxNTE0ODIzMXwxNDk0ODg5MjAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789721059542">
          <titulo>O Preço do Sal</titulo>
          <cod_autor>19537</cod_autor>
          <editora />
          <npaginas>254</npaginas>
          <preco>20.09</preco>
          <imagem>https://img.wook.pt/images/o-preco-do-sal-patricia-highsmith/MXwyMjUwNDl8MzQxMDc4fDEzODM1MjMyMDAwMDA=/260x</imagem>
     </livro>
     <livro isbn="9789721046085">
          <titulo>O Talentoso Mr. Ripley</titulo>
          <cod_autor>19537</cod_autor>
          <editora />
          <npaginas>232</npaginas>
          <preco>19.08</preco>
          <imagem>https://img.wook.pt/images/o-talentoso-mr-ripley-patricia-highsmith/MXw2NTY3MXw5NTczOHwxNDg0MDkyODAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789726620587">
          <titulo>Inocência Perversa</titulo>
          <cod_autor>19537</cod_autor>
          <editora>Gradiva</editora>
          <npaginas>324</npaginas>
          <preco>10.10</preco>
          <imagem>https://img.wook.pt/images/inocencia-perversa-patricia-highsmith/MXw2MDA3NXw5MDE0MnwxNDYzNjk4ODAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789892341422">
          <titulo>Juntos ao Luar</titulo>
          <cod_autor>4895</cod_autor>
          <editora>Edições Asa</editora>
          <npaginas>304</npaginas>
          <preco>15.21</preco>
          <imagem>https://img.wook.pt/images/juntos-ao-luar-nicholas-sparks/MXwyMTM3ODkxNHwxNzI1ODc3MHwxNTE3MzU2ODAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789892336930">
          <titulo>Só Nós Dois</titulo>
          <cod_autor>4895</cod_autor>
          <editora>Edições Asa</editora>
          <npaginas>568</npaginas>
          <preco>18.90</preco>
          <imagem>https://img.wook.pt/images/so-nos-dois-nicholas-sparks/MXwxODkwOTkxNHwxNDY0MDkxNXwxNDc3NTIyODAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789892333786">
          <titulo>No teu Olhar</titulo>
          <cod_autor>4895</cod_autor>
          <editora>Edições Asa</editora>
          <npaginas>520</npaginas>
          <preco>18.50</preco>
          <imagem>https://img.wook.pt/images/no-teu-olhar-nicholas-sparks/MXwxNjk1MzU5MnwxMjU3NDMxN3wxNDQ2NDIyNDAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789892337340">
          <titulo>Um Momento Inesquecível</titulo>
          <cod_autor>4895</cod_autor>
          <editora>Edições Asa</editora>
          <npaginas>208</npaginas>
          <preco>15.90</preco>
          <imagem>https://img.wook.pt/images/um-momento-inesquecivel-nicholas-sparks/MXwxOTE3MzM3MHwxNDk1NzkwOHwxNDg3ODk0NDAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789892335568">
          <titulo>Corações em Silêncio</titulo>
          <cod_autor>4895</cod_autor>
          <editora>Edições Asa</editora>
          <npaginas>368</npaginas>
          <preco>16.90</preco>
          <imagem>https://img.wook.pt/images/coracoes-em-silencio-nicholas-sparks/MXwxNzk3NDM1MnwxMzYyMzMwMHwxNDYzOTU4MDAwMDAw/260x</imagem>
     </livro>
     <livro isbn="978-972-37-1774-7">
          <titulo>Livro do Desassossego</titulo>
          <cod_autor>2103</cod_autor>
          <editora>Assírio &amp; Alvim</editora>
          <npaginas>480</npaginas>
          <preco>15.40</preco>
          <imagem>https://img.wook.pt/images/livro-do-desassossego-fernando-pessoa/MXwxMTIzNzI5MXwxNjEyODE1OHwxNTA4ODg2MDAwMDAw/260x</imagem>
     </livro>
     <livro isbn="978-972-37-1787-7">
          <titulo>Livro do desassossego</titulo>
          <cod_autor>2103</cod_autor>
          <editora>Assírio &amp; Alvim</editora>
          <npaginas>480</npaginas>
          <preco>11.62</preco>
          <imagem>https://img.wook.pt/images/livro-do-desassossego-fernando-pessoa/MXwxNTkyNzI2NXwxNzMwNjY2MHwxNTE5Nzc2MDAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789896714239">
          <titulo>Fausto</titulo>
          <cod_autor>2103</cod_autor>
          <editora>Tinta da China</editora>
          <npaginas>576</npaginas>
          <preco>16.20</preco>
          <imagem>https://img.wook.pt/images/fausto-fernando-pessoa/MXwyMTY4MzI5MnwxNzUzNDk1OHwxNTIyMTA1MjAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789897023897">
          <titulo>Tenho Medo de Partir</titulo>
          <cod_autor>2103</cod_autor>
          <editora>Editora Guerra &amp; Paz</editora>
          <npaginas>192</npaginas>
          <preco>12.15</preco>
          <imagem>https://img.wook.pt/images/tenho-medo-de-partir-fernando-pessoa/MXwyMTgyNTgyOHwxNzY3OTIyM3wxNTI0MDkyNDAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789897023736">
          <titulo>Absinto, Ópio, Tabaco e Outros Fumos</titulo>
          <cod_autor>2103</cod_autor>
          <editora>Editora Guerra &amp; Paz</editora>
          <npaginas>112</npaginas>
          <preco>10.80</preco>
          <imagem>https://img.wook.pt/images/absinto-opio-tabaco-e-outros-fumos-fernando-pessoa/MXwyMTUyMTAxOXwxNzM2ODIxOXwxNTIwMzgwODAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789722524223">
          <titulo>O Alquimista</titulo>
          <cod_autor>20202</cod_autor>
          <editora>11 X 17</editora>
          <npaginas>200</npaginas>
          <preco>8.00</preco>
          <imagem>https://img.wook.pt/images/o-alquimista-paulo-coelho/MXwxNTIzNzEzOXwxMDcyNTQ3NXwxMzgzNTIzMjAwMDAw/260x</imagem>
     </livro>
     <livro isbn="9789896875053">
          <titulo>Hippie</titulo>
          <cod_autor>20202</cod_autor>
          <editora>Pergaminho</editora>
          <npaginas>224</npaginas>
          <preco>14.94</preco>
